import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import storesRouter from "./stores";
import adminRouter from "./admin";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import inventoryRouter from "./inventory";
import customizationRouter from "./customization";
import productImagesRouter from "./product_images";
import statsRouter from "./stats";
import variantsRouter from "./variants";
import { perProductRouter as reviewsPerProductRouter, allReviewsRouter } from "./reviews";
import restaurantTablesRouter from "./restaurant/tables";
import restaurantOrdersRouter from "./restaurant/orders";
import restaurantDailyMenuRouter from "./restaurant/daily-menu";
import restaurantStatsRouter from "./restaurant/stats";
import salesRouter from "./sales";
import clientsRouter from "./clients";
import supportTicketsRouter from "./support-tickets";
import activeAnnouncementsRouter from "./announcements";
import analyticsRouter from "./analytics";
import restaurantAnalyticsRouter from "./restaurant/analytics";
import publicRouter from "./public";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/stores", storesRouter);
router.use("/stores/me", customizationRouter);
router.use("/admin", adminRouter);
router.use("/categories", categoriesRouter);
router.use("/products", productsRouter);
router.use("/products", productImagesRouter);
router.use("/products/:productId/variants", variantsRouter);
router.use("/products/:productId/reviews", reviewsPerProductRouter);
router.use("/reviews", allReviewsRouter);
router.use("/inventory", inventoryRouter);
router.use("/stats", statsRouter);
router.use("/restaurant/tables", restaurantTablesRouter);
router.use("/restaurant/orders", restaurantOrdersRouter);
router.use("/restaurant/daily-menu", restaurantDailyMenuRouter);
router.use("/restaurant/stats", restaurantStatsRouter);
router.use("/sales", salesRouter);
router.use("/clients", clientsRouter);
router.use("/support-tickets", supportTicketsRouter);
router.use("/active-announcements", activeAnnouncementsRouter);
router.use("/analytics", analyticsRouter);
router.use("/restaurant/analytics", restaurantAnalyticsRouter);
router.use("/public", publicRouter);

export default router;
